#!/usr/local/bin/php -f
<?php

if (!isset($argv[1]))
{
    die("Usage: r2d2 <start | status | reload | restart | stop | kill>\n");
}

require_once(__DIR__."/src/ProcessManager.php");

new R2D2\ProcessManager($argv[1]);
