#!/usr/local/bin/php -f
<?php

if (!isset($argv[1]))
{
    die("Usage: r2d2 <start | stop | status ...>\n");
}
require_once(__DIR__ . "/src/ProcessManager.php");
new \rpurinton\r2d2\ProcessManager($argv[1]);
